// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Persistence.Contexts;

#nullable disable

namespace ProductService.Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UK_Categories_Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("68a7e592-7610-4458-a8a9-2e83bb9e5a12"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Computer"
                        },
                        new
                        {
                            Id = new Guid("53c0c7ae-747e-4dd6-9c55-4e2beb088a09"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("ProductService.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Name" }, "UK_Product_Name")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b14f4b6-e6da-4f21-ab8f-78e5ef83b487"),
                            CategoryId = new Guid("68a7e592-7610-4458-a8a9-2e83bb9e5a12"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/acer/thumb/142883-4_small.jpg",
                            Name = "LENOVO AIO 3 INTEL CORE İ5 12450H 3.3 GHZ 8 GB 512 GB",
                            Price = 16000m
                        },
                        new
                        {
                            Id = new Guid("710cde63-a433-4f0e-93a1-f175d97ec869"),
                            CategoryId = new Guid("68a7e592-7610-4458-a8a9-2e83bb9e5a12"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/grundig/thumb/0001-layer-3_small.jpg",
                            Name = "EXPER XERA XC136 INTEL CORE İ5 13400F 2.5GHZ 16GB",
                            Price = 15000m
                        },
                        new
                        {
                            Id = new Guid("fbb71f16-638a-4c7d-85d6-98a86ee5cf74"),
                            CategoryId = new Guid("68a7e592-7610-4458-a8a9-2e83bb9e5a12"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/hp/thumb/146251-1_small.jpg",
                            Name = "HP 898B7EA INTEL CORE İ5 1335U 3.4 GHZ 8 GB 512 GB",
                            Price = 16500m
                        },
                        new
                        {
                            Id = new Guid("e3882ee9-2c8e-4d85-90b4-86217149fe1a"),
                            CategoryId = new Guid("68a7e592-7610-4458-a8a9-2e83bb9e5a12"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/philips/thumb/140996-1_large.jpg",
                            Name = "EXPER DIAMOND DEX600 INTEL CORE İ5 11400 2.6GHZ 8GB 256GB SSD INTEL UHD730",
                            Price = 35000m
                        },
                        new
                        {
                            Id = new Guid("c9ba11e2-0a37-416b-88f1-ff272ec75fb1"),
                            CategoryId = new Guid("68a7e592-7610-4458-a8a9-2e83bb9e5a12"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/exper/thumb/144179-1_large.jpg",
                            Name = "CASPER Excalibur E650 İ5 12400F 2.5GHZ 32GB 500GB",
                            Price = 15400m
                        },
                        new
                        {
                            Id = new Guid("f173c6d3-1222-4742-8c69-5de31e63b602"),
                            CategoryId = new Guid("53c0c7ae-747e-4dd6-9c55-4e2beb088a09"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/apple/thumb/129895-1_large.jpg",
                            Name = "iPhone 13 128 Gb Akıllı Telefon Mavi",
                            Price = 25000m
                        },
                        new
                        {
                            Id = new Guid("13fd2cc8-7c81-49d8-914e-84ddaebdf725"),
                            CategoryId = new Guid("53c0c7ae-747e-4dd6-9c55-4e2beb088a09"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/apple/thumb/129885-1_large.jpg",
                            Name = "iPhone 13 128 Gb Akıllı Telefon Yıldız Işığı",
                            Price = 12000m
                        },
                        new
                        {
                            Id = new Guid("c86535ef-33b9-4367-b9dd-789a6fd0a728"),
                            CategoryId = new Guid("53c0c7ae-747e-4dd6-9c55-4e2beb088a09"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/apple/thumb/129743-1_large.jpg",
                            Name = "Samsung Galaxy A15 6/128 Gb Akıllı Telefon Siyah",
                            Price = 35000m
                        },
                        new
                        {
                            Id = new Guid("734d45b1-fbc5-41ac-b423-31cc0bf48031"),
                            CategoryId = new Guid("53c0c7ae-747e-4dd6-9c55-4e2beb088a09"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/tcl/thumb/142148-1_large.jpg",
                            Name = "Xiaomi Redmi 12 8/128 GB Gece Yarısı Siyahı Akıllı Telefon",
                            Price = 25400m
                        });
                });

            modelBuilder.Entity("ProductService.Domain.Product", b =>
                {
                    b.HasOne("ProductService.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductService.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
